#!/bin/sh
#
# File:           mountkindle
# Maintainer:     Xiaodong Xu <xxdlhy@gmail.com>
# Last modified:  14/02/11 19:30:04

mount -t vfat /dev/sdb1 /mnt/kindle -o uid=1000,gid=100,utf8,dmask=027,fmask=137
